// <auto-generated />
using DemoMVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DemoMVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231030050445_Create_table_Person")]
    partial class Create_table_Person
    {
        /// <inheritdoc /> Vu Ngoc Tuyen 2021050715
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("DemoMVC.Models.Person", b =>
                {
                    b.Property<int>("PersonID")//Vu Ngoc Tuyen 2021050715
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");//Vu Ngoc Tuyen 2021050715

                    b.Property<string>("FullName")//Vu Ngoc Tuyen 2021050715
                        .IsRequired()
                        .HasColumnType("TEXT");//Vu Ngoc Tuyen 2021050715

                    b.HasKey("PersonID");//Vu Ngoc Tuyen 2021050715

                    b.ToTable("Person");//Vu Ngoc Tuyen 2021050715
                });
#pragma warning restore 612, 618//Vu Ngoc Tuyen 2021050715
        }
    }
}
